name: CI Pipeline

on:
  push:
    branches: [main, master, staging, develop]
  pull_request:
    branches: [main, master, staging, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint --if-present
        continue-on-error: true
      
      - name: Run typecheck
        run: npm run typecheck --if-present
        continue-on-error: true
      
      - name: Run tests
        run: npm run test --if-present
        continue-on-error: true
      
      - name: Build project
        run: npm run build
      
      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Check bundle size
        run: |
          echo "Build successful! Bundle analysis:"
          ls -lh dist/assets/ || echo "No assets directory found"
